#pragma config(Sensor, dgtl1,  rightEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,   sensorQuadEncoder)
#pragma config(Sensor, in2,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl5,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl6,  RangeFinder,    sensorSONAR_cm)
#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Motor,  port2,           leftMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopAllMotors(){
  motor[rightMotor] = 0;
  motor[leftMotor] = 0;
}
void driveForward(int dist)
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(dist > abs(SensorValue[leftEncoder])){

		if(SensorValue[rightEncoder] == SensorValue[leftEncoder]){
			motor[rightMotor] = 80;
			motor[leftMotor]  = 80;
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
			motor[rightMotor] = 60;
			motor[leftMotor]  = 80;
		}
		else{
			motor[rightMotor] = 80;
			motor[leftMotor]  = 60;
		}
	}
}
void turn90Degrees(int left,int right){
	motor[leftMotor] = left;
  motor[rightMotor] = right;
  wait1Msec(523);
}


task drivePath()//verk 2.3
{
	int dist = 760;

	while(vexRT[Btn8U]==0){
	driveForward(dist);
	stopAllMotors();

	turn90Degrees(-70,70);//haegri beyga
	stopAllMotors();

	for (int i = 1; i <= 2; i++){
		driveForward(dist);
		stopAllMotors();
		turn90Degrees(70,-70);
		stopAllMotors();
	}

	driveForward(dist);
	stopAllMotors();
	turn90Degrees(-127,127);
	stopAllMotors();
}

}



task JoyStickControll ()//verkefni 3
{

  while (vexRT[Btn8U] == 0){
		motor[leftMotor] = vexRT[Ch3] / 2;
		motor[rightMotor] = vexRT[Ch2] / 2;

		if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[pushBtn] == 0){
				motor[armMotor] = 60;
			}
		}
		else if(vexRT[Btn5U] == 1)
		{
				motor[armMotor] = -60;
		}
		else
		{
			motor[armMotor] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[clawMotor] = 60;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[clawMotor] = -60;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
	stopAllMotors();

}



task driveAndTurnAuto(){//verk4
  while (true)
  	{
    if(SensorValue(RangeFinder) < 55 || SensorValue(RangeFinder) == -1 ){
				turn90Degrees(70,-70);
    }
    if(SensorValue(lightSensor) > 300){
    	stopAllMotors();
  	}
  	else{
    	driveForward(100);
  	}
	}
}


task driveAfterLine()//verk 5
{

	int threshold =2200;
	int speed = 63;
	while(true)//vexRT[Btn8U]==0)
	{
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}

	}

}
task main()
{

	while(true){
		stopAllMotors();
 if(vexRT[Btn7L] == 1){//verkefni 2.3
	stopAllMotors();
 StopTask(driveAndTurnAuto);
	StopTask(JoyStickControll);
  StopTask(driveAfterLine);
	StartTask(drivePath);
	}

 if(vexRT[Btn7U] == 1){//verkefni 3
   stopAllMotors();
		StopTask(driveAndTurnAuto);
		StopTask(drivePath);
		StopTask(driveAfterLine);
	  StartTask(JoyStickControll);
	}

 if(vexRT[Btn7R] == 1){//verkefni 4
   stopAllMotors();
  StopTask(JoyStickControll);
	StopTask(drivePath);
  StopTask(driveAfterLine);
	StartTask(driveAndTurnAuto);
	}

 if(vexRT[Btn7D] == 1){//verkefni 5
   stopAllMotors();
  StopTask(driveAndTurnAuto);
	StopTask(drivePath);
	StopTask(JoyStickControll);
	StartTask(driveAfterLine);
	}
}
}
