#pragma config(Sensor, dgtl3,  rightEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  leftEncoder,   sensorQuadEncoder)

#pragma config(Sensor, in4,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgt6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgt8,  RangeFinder,    sensorSONAR_cm)

#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)

#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task stopAllMotors(){
  motor[rightMotor] = 0;
  motor[leftMotor] = 0;
}


task main(){
  while (SensorValue[pushBtn] == 0){
    while(SensorValue(RangeFinder) < 55 || SensorValue(RangeFinder) == -1 ){
      motor[rightMotor] = -60;
      motor[leftMotor] = 60;
      wait1Msec(535);
    }
    if(SensorValue(lightSensor) > 300){
    	StartTask(stopAllMotors);
  	}
  	else{
    	if(SensorValue[rightEncoder] == SensorValue[leftEncoder]){
			motor[rightMotor] = 80;
			motor[leftMotor]  = 80;
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
			motor[rightMotor] = 60;
			motor[leftMotor]  = 80;
		}
		else{
			motor[rightMotor] = 80;
			motor[leftMotor]  = 60;
		}
  	}
	}
}
