#pragma config(Sensor, dgtl3,  rightEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  leftEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           rightMotor,     tmotorVex269, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Forward for Distance with Encoders -                                *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward then turn90Degrees, driveForward, turn90Degrees  *|
|*  driveForward, turn90Degrees, driveForward
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  																																										        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Shaft Encoder     Right side                        *|
|*    Digital - Port 3,4  leftEncoder         VEX Shaft Encoder     Left side                         *|
\*----------------------------------------------------------------------------------------------------*/


void driveForward(int dist)
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(dist > abs(SensorValue[leftEncoder])){

		if(SensorValue[rightEncoder] == SensorValue[leftEncoder]){
			motor[rightMotor] = 80;
			motor[leftMotor]  = 80;
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder])){
			motor[rightMotor] = 60;
			motor[leftMotor]  = 80;
		}
		else{
			motor[rightMotor] = 80;
			motor[leftMotor]  = 60;
		}
	}
}

void stopMotors(){
	motor[rightMotor] = 0;
  motor[leftMotor] = 0;
  wait1Msec(800);
};

void turn90Degrees(int left,int right){
	motor[leftMotor] = left;
  motor[rightMotor] = right;
  wait1Msec(800);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
	const int dist = 562;

	driveForward(dist * i);
	stopMotors();

	turn90Degrees(127,-127);//haegri beyga
	stopMotors();

	for (int i = 1; i <= 2; i++){
		driveForward(dist * i);
		stopMotors();
		turn90Degrees(-127,127);
		stopMotors();
	}

	driveForward(dist * i);
	stopMotors();
	turn90Degrees(127,-127);
	stopMotors();


}
