#pragma config(Motor, port1, rightMotor, tmotorNormal, openLoop, reversed)
#pragma config(Motor, port10, leftMotor, tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/
int time = 1300; //Tmi fyrir hversu lengi  ert a keyra
void driveForward(int counter){ // fall fyrir a fara afram
	motor[rightMotor] = 80; //nota 80 ekki 127
	motor[leftMotor]  = 80; // nota 80 ekki 127
	wait1Msec(time*counter); // tmi sinnum hversu oft hann a a keyra
}
void driveBackwards(int counter){ // fall fyrir a keyra afturabak
	motor[rightMotor] = -80; //nota -80 ekki -127
	motor[leftMotor]  = -80; // nota -80 ekki -127
	wait1Msec(time*counter); //timi sinnum hversu oft hann a ad keyra
}
void stopmotors(){ // stoppa alla motora
	motor[rightMotor] = 0; // haegri motor fer i 0
	motor[leftMotor]  = 0; //vinstri motor fer i 0
}
//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	for(int i = 1; i <= 5 ; i++){ //for lykkja fyrir keyrslunna
		if(i % 2){ //ef a verur engin afgangur
			driveForward(i); //a keyrir hann afram
			stopmotors(); //of stoppar svo og heldur afram
		}
		else{ //annars
			driveBackwards(i); //keyrir hann aftur abak
			stopmotors(); //og stoppar
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
