#pragma config(Sensor, in1,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Motor,  port3,           leftMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 63;



task drive()
{

	int threshold =2800;

	while(true)
	{
		if(SensorValue[pushBtn] == 1){
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
	}

}
task main()
{
	int threshold =2500;

	while(true)
	{
		if(SensorValue[pushBtn] == 1){
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
	}
}
