#pragma config(Sensor, in3,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in5,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Motor,  port2,           leftMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 63;


task drive()
{

	int threshold =2200;
	/*
	while(true)
	{
		if(SensorValue(lineFollowerRIGHT) <= SensorValue(lineFollowerCENTER) && SensorValue(lineFollowerCENTER) >= SensorValue(lineFollowerLEFT))
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		else if(SensorValue(lineFollowerRIGHT) >= SensorValue(lineFollowerCENTER))
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = (speed/2);
		}
		else if(SensorValue(lineFollowerLEFT) >= SensorValue(lineFollowerCENTER))
		{
			motor[leftMotor]  = (speed/2);
			motor[rightMotor] = speed;
		}
			wait1Msec(20);
  }
	*/

	while(true)
	{
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
		/*
		else if(SensorValue(lineFollowerLEFT) > 200 && SensorValue(lineFollowerLEFT) >200 &&SensorValue(lineFollowerLEFT) >200){
			motor[leftMotor]  = 0;
			motor[rightMotor] = 0;
	}*/
		wait1Msec(20);
	}

}
task main()
{

	StartTask(drive);
 	while(vexRT[Btn8U] == 1){}
}
