#pragma config(Sensor, in1,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in5,    potentm,        sensorPotentiometer)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 63;

void arm(int pos){//potentiometer 3160-3100 fyrir nedsta, 2260 fyrir mid, 1100 fyrir hatt
	if (pos < SensorValue[potentm]){
		while(pos < SensorValue[potentm]){
		motor[armMotor]=40;//nidur
		}
	}
	if (pos > SensorValue[potentm]){
		while(pos > SensorValue[potentm]){
		motor[armMotor]=-40;//upp
		}
	}
}



task drive()
{

	int threshold =2800;

	while(true)
	{
		if(SensorValue[pushBtn] == 1){
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
	}

}
task main()
{
	int threshold =2500;
	int half=0;
	motor[clawMotor] = 80;

	while(true)
	{
		arm(3100);
		if(SensorValue[pushBtn] == 1){
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
		//-*--*-verk 6 kodi eftir dessa linu-*--*-//
		if(SensorValue(lineFollowerRIGHT) < threshold && SensorValue(lineFollowerCENTER) < threshold && SensorValue(lineFollowerLEFT) < threshold && half == 0)
		{
			half = 1;

			//motor[clawMotor] = -40;//loka

			arm(3100);

		}
		if(SensorValue(lineFollowerCENTER) > threshold && half == 1){
			half = 2;
		}
		if(SensorValue(lineFollowerRIGHT) < threshold && SensorValue(lineFollowerCENTER) < threshold && SensorValue(lineFollowerLEFT) < threshold && half == 2)
		{
			motor[armMotor] = 20;//nidur
			motor[clawMotor] = 40;//opna
		}
	}
}
