#pragma config(Sensor, in1,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in2,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in5,    potentm,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  left_encoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right_encoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold =2000;
//int threshold =2500;
//int threshold =2800;
float correction = 0.3;
//int speed = 90;
//int speed = 63;
//int speed = 50;
int speed = 45;
int encoder=0;
string nav = "";
void arm(int pos){//potentiometer 3160-3100 fyrir nedsta, 2260 fyrir mid, 1100 fyrir hatt
	if (pos > SensorValue[potentm]){
		while(pos > SensorValue[potentm]){
			motor[armMotor]=40;//nidur
			if (pos < SensorValue[potentm]){break;}
			else if (3200 < SensorValue[potentm]){break;}
		}
		motor[armMotor]=0;
	}
	else if (pos < SensorValue[potentm]){
		while(pos < SensorValue[potentm]){
			motor[armMotor]=-40;//upp
			if (pos > SensorValue[potentm]){break;}
			else if (1100 > SensorValue[potentm]){break;}
		}
		motor[armMotor]=0;
	}
}

void claw(int grip){
	if (grip == 1){//open
		motor[clawMotor] = 80;
		wait10Msec(100);
	}
	else if (grip == 0){//close
		motor[clawMotor] = -80;
		wait10Msec(100);
	}
}

/*task drive()
{

	int threshold =2800;

	while(true)
	{
		if(SensorValue[pushBtn] == 1){
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = 0;
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = 0;
			motor[rightMotor] = speed;
		}
	}

}*/
task main()
{
	//int half=0;
	//motor[clawMotor] = 80;
	//arm(2000);

	while(encoder<6000)
	{
		if(SensorValue[pushBtn] == 1){
			claw(1);
			break;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold)
		{
			//motor[leftMotor] = speed;
			motor[leftMotor]  = 100;
			//motor[rightMotor] = -speed*correction;
			motor[rightMotor] = 0;
			nav = "R";
		}
		if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			//motor[leftMotor]  = -speed*correction;
			motor[leftMotor]  = 0;
			//motor[rightMotor] = speed;
			motor[rightMotor] = 100;
			nav = "L";
		}
		if(SensorValue(lineFollowerCENTER) > threshold)
		{
			motor[leftMotor]  = speed;
			motor[rightMotor] = speed;
		}
		/*else{
			if (nav == "R"){
					motor[leftMotor]  = speed*2;
					//motor[leftMotor]  = speed;
					//motor[rightMotor] = 0;
					motor[rightMotor] = -speed;
				}
			if (nav == "L"){
					motor[leftMotor]  = -speed;
					//motor[leftMotor]  = 0;
					motor[rightMotor] = speed*2;
					//motor[rightMotor] = speed;
				}
		}*/
		/*if(SensorValue(lineFollowerLEFT) > threshold)
		{//faeri linesensorana naer jordinni og kikja a haegri motorinn keyrir stanslaust
			motor[leftMotor]  = -speed*correction;
			motor[rightMotor] = speed;
		}*/

		//-*--*-verk 6 kodi eftir dessa linu-*--*-//
		encoder= (abs(SensorValue[left_encoder])+abs(SensorValue[right_encoder]))/2;

		/*
		if(SensorValue(lineFollowerRIGHT) > threshold && SensorValue(lineFollowerCENTER) > threshold && SensorValue(lineFollowerLEFT) > threshold && half == 0)
		//if(SensorValue(lineFollowerRIGHT) < 2070 && SensorValue(lineFollowerCENTER) < 1650 && SensorValue(lineFollowerLEFT) < 2260 && half == 0)
		{
			half = 1;

			//motor[clawMotor] = -40;//loka

			arm(3100);

		}
		if(SensorValue(lineFollowerCENTER) < threshold && half == 1){
			half = 2;
		}
		if(SensorValue(lineFollowerRIGHT) > threshold && SensorValue(lineFollowerCENTER) > threshold && SensorValue(lineFollowerLEFT) > threshold && half == 2)
		{
			motor[armMotor] = 20;//nidur
			motor[clawMotor] = 40;//opna
		}
		*/
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
	}
	//*-*-*-*
	//byrja while loopid aftur eda einhvern likan while loop eftir ad vid erum viss velid getur farid til baka
	motor[leftMotor]  = 0;
	motor[rightMotor] = 0;
	claw(0);
	//wait10Msec(100);
}
